name: Normalize Major Version Tag
description: Create and update normalized major version tags for GitHub Actions based on semantic versioning tags
author: stairwaytowonderland

# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
branding:
  icon: tag
  color: red

inputs:
  dry-run:
    description: Dry run
    required: false
    default: 'false'
  github-token:
    description: GitHub token
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.js
